version: '3.5'
services:

  salary_db:
    container_name: salary_db
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - salary-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  salary_redis:
    container_name: salary_redis
    image: redis:5
    restart: always
    networks:
      - salary-network
    ports:
      - 6379:6379

  salary_app:
    container_name: salary_app
    depends_on:
      - salary_db
      - salary_redis
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - salary-network
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://salary_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=salary_redis
      - SPRING_DATA_REDIS_PORT=6379

networks:
  salary-network:

volumes:
  db_data: